# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-11 18:50
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField()),
                ('password', models.CharField(max_length=64)),
                ('password_next', models.CharField(max_length=64)),
                ('lecture_id', models.CharField(max_length=5)),
                ('description', models.CharField(max_length=200)),
                ('riddle', django.contrib.postgres.fields.jsonb.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='Maze',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('difficulty', models.IntegerField()),
                ('type', models.CharField(max_length=100)),
            ],
        ),
    ]
