# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-14 13:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LearnSecurity', '0002_remove_maze_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='level',
            name='description',
        ),
        migrations.RemoveField(
            model_name='level',
            name='lecture_id',
        ),
        migrations.RemoveField(
            model_name='level',
            name='password',
        ),
        migrations.RemoveField(
            model_name='level',
            name='password_next',
        ),
        migrations.RemoveField(
            model_name='level',
            name='riddle',
        ),
    ]
