# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-15 08:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LearnSecurity', '0004_level_maze'),
    ]

    operations = [
        migrations.AddField(
            model_name='maze',
            name='desc',
            field=models.CharField(default='Test', max_length=30),
            preserve_default=False,
        ),
    ]
