# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-15 11:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LearnSecurity', '0005_maze_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='level',
            name='description',
            field=models.CharField(default='Cat', max_length=200),
            preserve_default=False,
        ),
    ]
