# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-15 13:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LearnSecurity', '0006_level_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='level',
            old_name='description',
            new_name='short_description',
        ),
        migrations.AddField(
            model_name='level',
            name='program_description',
            field=models.CharField(default='desc', max_length=2000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='level',
            name='program_usage',
            field=models.CharField(default='usage', max_length=200),
            preserve_default=False,
        ),
    ]
