# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-15 13:08
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LearnSecurity', '0007_auto_20160815_1506'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='level',
            name='program_usage',
        ),
        migrations.AlterField(
            model_name='level',
            name='program_description',
            field=django.contrib.postgres.fields.jsonb.JSONField(),
        ),
    ]
