# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-13 17:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('LearnSecurity', '0008_auto_20160815_1508'),
    ]

    operations = [
        migrations.CreateModel(
            name='LevelStep',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level_step', models.IntegerField()),
                ('description', models.CharField(max_length=200)),
                ('help', models.CharField(max_length=200)),
                ('answer', models.CharField(max_length=200)),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LearnSecurity.Level')),
            ],
        ),
    ]
