# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-14 10:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LearnSecurity', '0009_levelstep'),
    ]

    operations = [
        migrations.AddField(
            model_name='levelstep',
            name='password',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
