# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-03 09:49
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LearnSecurity', '0011_auto_20161103_1044'),
    ]

    operations = [
        migrations.AddField(
            model_name='levelstep',
            name='description',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=''),
        ),
    ]
