# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-06 18:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LearnSecurity', '0012_levelstep_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='maze',
            name='how_to',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
