# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-08 19:09
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('LearnSecurity', '0014_passwordrecoverykey'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordrecoverykey',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
