# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-15 15:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LearnSecurity', '0015_auto_20170108_2009'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='level',
            name='program_description',
        ),
        migrations.RemoveField(
            model_name='levelstep',
            name='description',
        ),
    ]
